version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: ['T: Build']
    reviewers: [JonasWanke]
    schedule:
      interval: weekly

  - package-ecosystem: dart
    directory: /
    labels: ['T: Build']
    reviewers: [JonasWanke]
    schedule:
      interval: weekly
