name: homepage
version: 3.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  black_hole_flutter: ^0.3.0
  collection: ^1.15.0
  dartx: ^0.6.0
  day_night_switcher: ^0.2.0
  flutter:
    sdk: flutter
  flutter_deep_linking: ^0.2.0-nullsafety.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.0.0-nullsafety
  get_it: ^6.0.0
  logger: ^1.0.0-nullsafety.0
  rxdart: ^0.26.0
  streaming_shared_preferences:
    git:
      url: https://github.com/JonasWanke/streaming_shared_preferences.git
      ref: a460743730d4653176455747362579a76f542e18
  supercharged: ^2.0.0-nullsafety.2
  todo: ^2.0.0
  url_launcher: ^6.0.1

dev_dependencies:
  extra_pedantic: ^1.3.0

flutter:
  generate: true
  uses-material-design: true
