name: homepage
version: 3.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  assorted_layout_widgets: ^8.0.4
  day_night_switcher: ^0.2.0
  flutter:
    sdk: flutter
  flutter_deep_linking: ^0.2.1
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.4.0
  just_the_tooltip: ^0.0.12
  supernova_flutter:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_flutter
      ref: ee91e4b530c1a27323853d9b6b56ce66fb075e84

dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1

dependency_overrides:
  http: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
