name: homepage
publish_to: "none"
version: 3.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  basics: ^0.4.0+1
  black_hole_flutter: ^0.2.14
  collection: ^1.14.11
  dartx: ^0.5.0
  flutter:
    sdk: flutter
  flutter_deep_linking: ^0.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.11.0+1
  get_it: ^5.0.1
  logger: ^0.9.4
  rxdart: ^0.24.1
  streaming_shared_preferences: ^1.0.1
  time_machine: ^0.9.13
  todo: ^1.0.2
  url_launcher: ^5.7.10

dev_dependencies:
  build_runner: ^1.10.1
  extra_pedantic: ^1.2.0
  freezed: ^0.11.4
  intl_utils: ^1.8.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
