name: homepage
version: 3.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  assorted_layout_widgets: ^8.0.4
  day_night_switcher: ^0.2.0
  flutter:
    sdk: flutter
  flutter_deep_linking: ^0.2.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.8
  just_the_tooltip: ^0.0.12
  shared_preferences: ^2.2.2
  streaming_shared_preferences: ^2.0.0
  supernova_flutter:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_flutter
      ref: bd9109d8ce8504bf6786b8f38813a20ae86f7544

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
