name: homepage
version: 3.0.0
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: '>=3.22.0'

dependencies:
  assorted_layout_widgets: ^9.0.2
  day_night_switcher: ^0.2.0
  flutter:
    sdk: flutter
  flutter_deep_linking: ^0.2.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  just_the_tooltip: ^0.0.12
  shared_preferences: ^2.2.2
  streaming_shared_preferences: ^2.0.0
  supernova_flutter:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_flutter
      ref: c568672838f2982d0b04562f33b42f6bafa85f70

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
