name: homepage
version: 3.0.0
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  align_positioned: ^3.0.0
  assorted_layout_widgets: ^8.0.4
  black_hole_flutter: ^1.0.1
  collection: ^1.15.0
  dartx: ^1.1.0
  day_night_switcher: ^0.2.0
  flutter:
    sdk: flutter
  flutter_deep_linking: ^0.2.1
  flutter_hooks: ^0.18.6
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.4.0
  get_it: ^7.1.3
  intl: ^0.18.0
  just_the_tooltip: ^0.0.12
  logger: ^1.0.0-nullsafety.0
  rxdart: ^0.27.0
  sliver_tools: ^0.2.9
  streaming_shared_preferences: ^2.0.0
  todo: ^2.0.0
  tuple: ^2.0.1
  url_launcher: ^6.0.1

dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
