name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [main]

env:
  JAVA_VERSION: 12.x
  FLUTTER_CHANNEL: stable
  FLUTTER_VERSION: 3.7.7

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - run: flutter pub get
      - run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JONAS_WANKE }}'
          channelId: live
          projectId: jonas-wanke
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
